FROM ajymau/ubi-maven:0.3.1 AS builder

RUN  mkdir -p /opt/ol \
  && mkdir -p /stacks/java-openliberty/starterapp

RUN chmod -R 777 /stacks/java-openliberty/starterapp

COPY ./LICENSE /licenses/
ADD ./starterapp/src /stacks/java-openliberty/starterapp/src
COPY ./starterapp/pom.xml /stacks/java-openliberty/starterapp/

WORKDIR /stacks/java-openliberty/starterapp
RUN mvn -DserverName=tmp liberty:create liberty:install-feature dependency:go-offline
RUN rm -rf ./target/liberty/wlp/usr/servers/tmp

FROM ajymau/ubi-maven:0.3.1
RUN mkdir -p /opt/ol
COPY --from=builder /root/.m2 /root/.m2
COPY --from=builder /stacks/java-openliberty/starterapp/target/liberty /opt/ol
